name: Build and publish release
on:
  push:
    tags:
      - 'v?[0-9].[0-9].[0-9]'

env:
  tag: ${{ github.ref_name }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y zsh

      - run: export tagversion=${tag#v}
        shell: zsh {0}
      - run: export tagmajorversion=${${tag#v}%.*.*}
        shell: zsh {0}

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USER || secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish Docker container
        run: |
          docker buildx build . \
            -t clairelizbet/discord-sudo:latest \
            -t "clairelizbet/discord-sudo:${tagversion}" \
            -t "clairelizbet/discord-sudo:${tagmajorversion}" \
            --push
        shell: zsh {0}

      - run: export releasenotes=$(< ${GITHUB_WORKSPACE}/.github/release.md)
        shell: zsh {0}
      - run: export releasenotes=${releasenotes:gs/'${tagversion}'/${tagversion}}
        shell: zsh {0}
      - run: export releasenotes=${releasenotes:gs/'${tagmajorversion}'/${tagmajorversion}}
        shell: zsh {0}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${tag}" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "v${tagversion} Update 🔧" \
            --notes "${releasenotes}"
        shell: zsh {0}
