name: Build and push Docker release

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'

env:
  tag: ${{ github.ref_name }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: clairelizbet/action-build@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER || secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}
          images: clairelizbet/discord-sudo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
